// Generated by scripts/generate-chart-registry.mjs — do not edit by hand.
// Re-run it after `node scripts/vendor-shadcn-reference.mjs`.
import type * as React from "react";

import { ChartAreaAxes } from "@/design-system/charts/chart-area-axes";
import { ChartAreaDefault } from "@/design-system/charts/chart-area-default";
import { ChartAreaGradient } from "@/design-system/charts/chart-area-gradient";
import { ChartAreaIcons } from "@/design-system/charts/chart-area-icons";
import { ChartAreaInteractive } from "@/design-system/charts/chart-area-interactive";
import { ChartAreaLegend } from "@/design-system/charts/chart-area-legend";
import { ChartAreaLinear } from "@/design-system/charts/chart-area-linear";
import { ChartAreaStackedExpand } from "@/design-system/charts/chart-area-stacked-expand";
import { ChartAreaStacked } from "@/design-system/charts/chart-area-stacked";
import { ChartAreaStep } from "@/design-system/charts/chart-area-step";
import { ChartBarActive } from "@/design-system/charts/chart-bar-active";
import { ChartBarDefault } from "@/design-system/charts/chart-bar-default";
import { ChartBarHorizontal } from "@/design-system/charts/chart-bar-horizontal";
import { ChartBarInteractive } from "@/design-system/charts/chart-bar-interactive";
import { ChartBarLabelCustom } from "@/design-system/charts/chart-bar-label-custom";
import { ChartBarLabel } from "@/design-system/charts/chart-bar-label";
import { ChartBarMixed } from "@/design-system/charts/chart-bar-mixed";
import { ChartBarMultiple } from "@/design-system/charts/chart-bar-multiple";
import { ChartBarNegative } from "@/design-system/charts/chart-bar-negative";
import { ChartBarStacked } from "@/design-system/charts/chart-bar-stacked";
import { ChartLineDefault } from "@/design-system/charts/chart-line-default";
import { ChartLineDotsColors } from "@/design-system/charts/chart-line-dots-colors";
import { ChartLineDotsCustom } from "@/design-system/charts/chart-line-dots-custom";
import { ChartLineDots } from "@/design-system/charts/chart-line-dots";
import { ChartLineInteractive } from "@/design-system/charts/chart-line-interactive";
import { ChartLineLabelCustom } from "@/design-system/charts/chart-line-label-custom";
import { ChartLineLabel } from "@/design-system/charts/chart-line-label";
import { ChartLineLinear } from "@/design-system/charts/chart-line-linear";
import { ChartLineMultiple } from "@/design-system/charts/chart-line-multiple";
import { ChartLineStep } from "@/design-system/charts/chart-line-step";
import { ChartPieDonutActive } from "@/design-system/charts/chart-pie-donut-active";
import { ChartPieDonutText } from "@/design-system/charts/chart-pie-donut-text";
import { ChartPieDonut } from "@/design-system/charts/chart-pie-donut";
import { ChartPieInteractive } from "@/design-system/charts/chart-pie-interactive";
import { ChartPieLabelCustom } from "@/design-system/charts/chart-pie-label-custom";
import { ChartPieLabelList } from "@/design-system/charts/chart-pie-label-list";
import { ChartPieLabel } from "@/design-system/charts/chart-pie-label";
import { ChartPieLegend } from "@/design-system/charts/chart-pie-legend";
import { ChartPieSeparatorNone } from "@/design-system/charts/chart-pie-separator-none";
import { ChartPieSimple } from "@/design-system/charts/chart-pie-simple";
import { ChartPieStacked } from "@/design-system/charts/chart-pie-stacked";
import { ChartRadarDefault } from "@/design-system/charts/chart-radar-default";
import { ChartRadarDots } from "@/design-system/charts/chart-radar-dots";
import { ChartRadarGridCircleFill } from "@/design-system/charts/chart-radar-grid-circle-fill";
import { ChartRadarGridCircleNoLines } from "@/design-system/charts/chart-radar-grid-circle-no-lines";
import { ChartRadarGridCircle } from "@/design-system/charts/chart-radar-grid-circle";
import { ChartRadarGridCustom } from "@/design-system/charts/chart-radar-grid-custom";
import { ChartRadarGridFill } from "@/design-system/charts/chart-radar-grid-fill";
import { ChartRadarGridNone } from "@/design-system/charts/chart-radar-grid-none";
import { ChartRadarLabelCustom } from "@/design-system/charts/chart-radar-label-custom";
import { ChartRadarLegend } from "@/design-system/charts/chart-radar-legend";
import { ChartRadarLinesOnly } from "@/design-system/charts/chart-radar-lines-only";
import { ChartRadarMultiple } from "@/design-system/charts/chart-radar-multiple";
import { ChartRadialGrid } from "@/design-system/charts/chart-radial-grid";
import { ChartRadialLabel } from "@/design-system/charts/chart-radial-label";
import { ChartRadialShape } from "@/design-system/charts/chart-radial-shape";
import { ChartRadialSimple } from "@/design-system/charts/chart-radial-simple";
import { ChartRadialStacked } from "@/design-system/charts/chart-radial-stacked";
import { ChartRadialText } from "@/design-system/charts/chart-radial-text";
import { ChartTooltipDefault } from "@/design-system/charts/chart-tooltip-default";
import { ChartTooltipIndicatorLine } from "@/design-system/charts/chart-tooltip-indicator-line";
import { ChartTooltipIndicatorNone } from "@/design-system/charts/chart-tooltip-indicator-none";
import { ChartTooltipLabelNone } from "@/design-system/charts/chart-tooltip-label-none";
import { ChartTooltipLabelCustom } from "@/design-system/charts/chart-tooltip-label-custom";
import { ChartTooltipLabelFormatter } from "@/design-system/charts/chart-tooltip-label-formatter";
import { ChartTooltipFormatter } from "@/design-system/charts/chart-tooltip-formatter";
import { ChartTooltipIcons } from "@/design-system/charts/chart-tooltip-icons";
import { ChartTooltipAdvanced } from "@/design-system/charts/chart-tooltip-advanced";

export type ChartCategory = "area" | "bar" | "line" | "pie" | "radar" | "radial" | "tooltip";

export type ChartEntry = {
  name: string;
  category: ChartCategory;
  variant: string;
  description: string;
  Component: React.ComponentType;
};

export const CHART_CATEGORIES: Array<{ id: ChartCategory; label: string; singular: string }> = [
  { id: "area", label: "Area Charts", singular: "Area Chart" },
  { id: "bar", label: "Bar Charts", singular: "Bar Chart" },
  { id: "line", label: "Line Charts", singular: "Line Chart" },
  { id: "pie", label: "Pie Charts", singular: "Pie Chart" },
  { id: "radar", label: "Radar Charts", singular: "Radar Chart" },
  { id: "radial", label: "Radial Charts", singular: "Radial Chart" },
  { id: "tooltip", label: "Tooltips", singular: "Tooltip" },
];

export const chartEntries: ChartEntry[] = [
  { name: "chart-area-axes", category: "area", variant: "axes", description: "An area chart with axes", Component: ChartAreaAxes },
  { name: "chart-area-default", category: "area", variant: "default", description: "A simple area chart", Component: ChartAreaDefault },
  { name: "chart-area-gradient", category: "area", variant: "gradient", description: "An area chart with gradient fill", Component: ChartAreaGradient },
  { name: "chart-area-icons", category: "area", variant: "icons", description: "An area chart with icons", Component: ChartAreaIcons },
  { name: "chart-area-interactive", category: "area", variant: "interactive", description: "An interactive area chart", Component: ChartAreaInteractive },
  { name: "chart-area-legend", category: "area", variant: "legend", description: "An area chart with a legend", Component: ChartAreaLegend },
  { name: "chart-area-linear", category: "area", variant: "linear", description: "A linear area chart", Component: ChartAreaLinear },
  { name: "chart-area-stacked-expand", category: "area", variant: "stacked-expand", description: "A stacked area chart with expand stacking", Component: ChartAreaStackedExpand },
  { name: "chart-area-stacked", category: "area", variant: "stacked", description: "A stacked area chart", Component: ChartAreaStacked },
  { name: "chart-area-step", category: "area", variant: "step", description: "A step area chart", Component: ChartAreaStep },
  { name: "chart-bar-active", category: "bar", variant: "active", description: "A bar chart with an active bar", Component: ChartBarActive },
  { name: "chart-bar-default", category: "bar", variant: "default", description: "A bar chart", Component: ChartBarDefault },
  { name: "chart-bar-horizontal", category: "bar", variant: "horizontal", description: "A horizontal bar chart", Component: ChartBarHorizontal },
  { name: "chart-bar-interactive", category: "bar", variant: "interactive", description: "An interactive bar chart", Component: ChartBarInteractive },
  { name: "chart-bar-label-custom", category: "bar", variant: "label-custom", description: "A bar chart with a custom label", Component: ChartBarLabelCustom },
  { name: "chart-bar-label", category: "bar", variant: "label", description: "A bar chart with a label", Component: ChartBarLabel },
  { name: "chart-bar-mixed", category: "bar", variant: "mixed", description: "A mixed bar chart", Component: ChartBarMixed },
  { name: "chart-bar-multiple", category: "bar", variant: "multiple", description: "A multiple bar chart", Component: ChartBarMultiple },
  { name: "chart-bar-negative", category: "bar", variant: "negative", description: "A bar chart with negative values", Component: ChartBarNegative },
  { name: "chart-bar-stacked", category: "bar", variant: "stacked", description: "A stacked bar chart with a legend", Component: ChartBarStacked },
  { name: "chart-line-default", category: "line", variant: "default", description: "A line chart", Component: ChartLineDefault },
  { name: "chart-line-dots-colors", category: "line", variant: "dots-colors", description: "A line chart with dots and colors", Component: ChartLineDotsColors },
  { name: "chart-line-dots-custom", category: "line", variant: "dots-custom", description: "A line chart with custom dots", Component: ChartLineDotsCustom },
  { name: "chart-line-dots", category: "line", variant: "dots", description: "A line chart with dots", Component: ChartLineDots },
  { name: "chart-line-interactive", category: "line", variant: "interactive", description: "An interactive line chart", Component: ChartLineInteractive },
  { name: "chart-line-label-custom", category: "line", variant: "label-custom", description: "A line chart with a custom label", Component: ChartLineLabelCustom },
  { name: "chart-line-label", category: "line", variant: "label", description: "A line chart with a label", Component: ChartLineLabel },
  { name: "chart-line-linear", category: "line", variant: "linear", description: "A linear line chart", Component: ChartLineLinear },
  { name: "chart-line-multiple", category: "line", variant: "multiple", description: "A multiple line chart", Component: ChartLineMultiple },
  { name: "chart-line-step", category: "line", variant: "step", description: "A line chart with step", Component: ChartLineStep },
  { name: "chart-pie-donut-active", category: "pie", variant: "donut-active", description: "A donut chart with an active sector", Component: ChartPieDonutActive },
  { name: "chart-pie-donut-text", category: "pie", variant: "donut-text", description: "A donut chart with text", Component: ChartPieDonutText },
  { name: "chart-pie-donut", category: "pie", variant: "donut", description: "A donut chart", Component: ChartPieDonut },
  { name: "chart-pie-interactive", category: "pie", variant: "interactive", description: "An interactive pie chart", Component: ChartPieInteractive },
  { name: "chart-pie-label-custom", category: "pie", variant: "label-custom", description: "A pie chart with a custom label", Component: ChartPieLabelCustom },
  { name: "chart-pie-label-list", category: "pie", variant: "label-list", description: "A pie chart with a label list", Component: ChartPieLabelList },
  { name: "chart-pie-label", category: "pie", variant: "label", description: "A pie chart with a label", Component: ChartPieLabel },
  { name: "chart-pie-legend", category: "pie", variant: "legend", description: "A pie chart with a legend", Component: ChartPieLegend },
  { name: "chart-pie-separator-none", category: "pie", variant: "separator-none", description: "A pie chart with no separator", Component: ChartPieSeparatorNone },
  { name: "chart-pie-simple", category: "pie", variant: "simple", description: "A simple pie chart", Component: ChartPieSimple },
  { name: "chart-pie-stacked", category: "pie", variant: "stacked", description: "A pie chart with stacked sections", Component: ChartPieStacked },
  { name: "chart-radar-default", category: "radar", variant: "default", description: "A radar chart", Component: ChartRadarDefault },
  { name: "chart-radar-dots", category: "radar", variant: "dots", description: "A radar chart with dots", Component: ChartRadarDots },
  { name: "chart-radar-grid-circle-fill", category: "radar", variant: "grid-circle-fill", description: "A radar chart with a grid and circle fill", Component: ChartRadarGridCircleFill },
  { name: "chart-radar-grid-circle-no-lines", category: "radar", variant: "grid-circle-no-lines", description: "A radar chart with a grid and circle fill", Component: ChartRadarGridCircleNoLines },
  { name: "chart-radar-grid-circle", category: "radar", variant: "grid-circle", description: "A radar chart with a grid and circle", Component: ChartRadarGridCircle },
  { name: "chart-radar-grid-custom", category: "radar", variant: "grid-custom", description: "A radar chart with a custom grid", Component: ChartRadarGridCustom },
  { name: "chart-radar-grid-fill", category: "radar", variant: "grid-fill", description: "A radar chart with a grid filled", Component: ChartRadarGridFill },
  { name: "chart-radar-grid-none", category: "radar", variant: "grid-none", description: "A radar chart with no grid", Component: ChartRadarGridNone },
  { name: "chart-radar-label-custom", category: "radar", variant: "label-custom", description: "A radar chart with a custom label", Component: ChartRadarLabelCustom },
  { name: "chart-radar-legend", category: "radar", variant: "legend", description: "A radar chart with a legend", Component: ChartRadarLegend },
  { name: "chart-radar-lines-only", category: "radar", variant: "lines-only", description: "A radar chart with lines only", Component: ChartRadarLinesOnly },
  { name: "chart-radar-multiple", category: "radar", variant: "multiple", description: "A radar chart with multiple data", Component: ChartRadarMultiple },
  { name: "chart-radial-grid", category: "radial", variant: "grid", description: "A radial chart with a grid", Component: ChartRadialGrid },
  { name: "chart-radial-label", category: "radial", variant: "label", description: "A radial chart with a label", Component: ChartRadialLabel },
  { name: "chart-radial-shape", category: "radial", variant: "shape", description: "A radial chart with a custom shape", Component: ChartRadialShape },
  { name: "chart-radial-simple", category: "radial", variant: "simple", description: "A radial chart", Component: ChartRadialSimple },
  { name: "chart-radial-stacked", category: "radial", variant: "stacked", description: "A radial chart with stacked sections", Component: ChartRadialStacked },
  { name: "chart-radial-text", category: "radial", variant: "text", description: "A radial chart with text", Component: ChartRadialText },
  { name: "chart-tooltip-default", category: "tooltip", variant: "default", description: "A stacked bar chart with a legend", Component: ChartTooltipDefault },
  { name: "chart-tooltip-indicator-line", category: "tooltip", variant: "indicator-line", description: "A stacked bar chart with a legend", Component: ChartTooltipIndicatorLine },
  { name: "chart-tooltip-indicator-none", category: "tooltip", variant: "indicator-none", description: "A stacked bar chart with a legend", Component: ChartTooltipIndicatorNone },
  { name: "chart-tooltip-label-none", category: "tooltip", variant: "label-none", description: "A stacked bar chart with a legend", Component: ChartTooltipLabelNone },
  { name: "chart-tooltip-label-custom", category: "tooltip", variant: "label-custom", description: "A stacked bar chart with a legend", Component: ChartTooltipLabelCustom },
  { name: "chart-tooltip-label-formatter", category: "tooltip", variant: "label-formatter", description: "A stacked bar chart with a legend", Component: ChartTooltipLabelFormatter },
  { name: "chart-tooltip-formatter", category: "tooltip", variant: "formatter", description: "A stacked bar chart with a legend", Component: ChartTooltipFormatter },
  { name: "chart-tooltip-icons", category: "tooltip", variant: "icons", description: "A stacked bar chart with a legend", Component: ChartTooltipIcons },
  { name: "chart-tooltip-advanced", category: "tooltip", variant: "advanced", description: "A stacked bar chart with a legend", Component: ChartTooltipAdvanced },
];
